### ISSUE TITLE
Installation issue on Ubuntu server 20

### ISSUE THREAD

**Issue by mlebeur** [bihealth/varfish-installer#1]
Hi,
I was trying to install VarFish on Ubuntu server 20 but I encounter several issues :
- make jannovar : ssh on localhost due to root permission (solved)
- make postgres : No package matching 'centos-release-scl' is available (unsolved)

I try to remove pretasks from plays/postgres.yml but the files are'nt find :

fatal: [postgres]: FAILED! => {
    "ansible_facts": {},
    "ansible_included_var_files": [],
    "changed": false,
    "message": "Could not find file\nSearched in:\n\t/home/***/varfish-installer/.imported_roles/bihealth.postgres_server/vars/[]\n\t/home/***/varfish-installer/.imported_roles/bihealth.postgres_server/[]\n\t/home/***/varfish-installer/.imported_roles/bihealth.postgres_server/tasks/vars/[]\n\t/home/***/varfish-installer/.imported_roles/bihealth.postgres_server/tasks/[]\n\t/home/***/varfish-installer/plays/vars/[]\n\t/home/***/varfish-installer/plays/[] on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}

Have you try on Ubuntu server 20 OS ?

Another question where is the Web client ?

Thank's a lot for your wonderfull work very inspiring.

Best

Manuel

**Comment by stolpeo** [comment]
Hello Manuel,

thank you very much for your interest in VarFish and your kind words! I also want to apologize that you experience issues with the installation. Currently, we are testing and revising the installation routine, so it is still work-in-progress, as you might have noticed.

That being said, the installation via ansible only supports CentOS 7 at this point in time. Unfortunately the manual is not clear in this. Technically, VarFish can also run on Ubuntu, and it is on our list to support other distributions in ansible as well. Do you have the possibility to set up a clean CentOS 7 for now?

My colleague @holtgrewe who primarily worked on the ansible scripts might add his thoughts (about next week). 

The github repository of VarFish Web is located here:
https://github.com/bihealth/varfish-server

And the checkout on the server instance will be located here:
/srv/varfish-web/master

Cheers,
  Oliver

**Comment by mlebeur** [comment]
Thanks a lor for your quick answer.
I will try with a CentOS7 distribution for now.
Thanks for the links.
Cheers,
Manuel

**Comment by mlebeur** [comment]
Hi,
I am trying to install VarFish on CentOS7 but I have some issue.
First the root must have permission to ssh in sshd_config (or sshkegen) for the make jannovar/postgres step.
Then during make varFish step I have an issue with on the "TASK [bihealth.postgres_client : on postgres host -- create database] "
postgres_client_host is not defined.
So I just add the variable definition in varfish-installer/inventories/production/group_vars/all/servers.yml as follow :
postgres_client_host: "127.0.0.1"
Then the make varFish goes to the TASK [bihealth.sodar_core_app : create virtualenv environment] .
Where i have this issue :
###################################
fatal: [varfish]: FAILED! => {
    "changed": true,
    "cmd": "set -xeo pipefail\ntrap \"rm -rf /srv/varfish-web/master-venv\" ERR\n$(which virtualenv) -p /usr/bin/python3.6 /srv/varfish-web/master-venv\n",
    "delta": "0:00:00.003513",
    "end": "2020-10-22 13:23:40.805035",
    "rc": 127,
    "start": "2020-10-22 13:23:40.801522"
}

STDERR:

+ trap 'rm -rf /srv/varfish-web/master-venv' ERR
++ which virtualenv
which: no virtualenv in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/pgsql-12/bin)
+ -p /usr/bin/python3.6 /srv/varfish-web/master-venv
/bin/bash: line 2: -p: command not found


MSG:

non-zero return code
###################################

I was thinking about a classical problem or name between python 2 vs 3 sor I create a symbolic link ln -s /bin/virtualenv-3 /bin/virtualenv.
Then when I rerun the make varFish I have similar issue but with much more logs.

###################################
fatal: [varfish]: FAILED! => {
    "changed": true,
    "cmd": "set -xeo pipefail\ntrap \"rm -rf /srv/varfish-web/master-venv\" ERR\nsource /srv/varfish-web/master-venv/bin/activate\npip install -r requirements/production.txt\n",
    "delta": "0:00:38.797057",
    "end": "2020-10-22 13:35:46.584571",
    "rc": 1,
    "start": "2020-10-22 13:35:07.787514"
}

STDOUT:

Collecting python-dotenv==0.9.1
  Downloading python_dotenv-0.9.1-py2.py3-none-any.whl (17 kB)
Collecting wheel==0.34.2
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
...

     building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psycopg
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext) -DPG_VERSION_NUM=90224 -I/usr/include/python3.6m -I. -I/usr/include -I/usr/include/pgsql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.6/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:28:0:
    ./psycopg/psycopg.h:36:22: fatal error: libpq-fe.h: No such file or directory
     #include <libpq-fe.h>
                          ^
    compilation terminated.

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/varfish-web/master-venv/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k96uu23d/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k96uu23d/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ede71h00/install-record.txt --single-version-externally-managed --compile --install-headers /srv/varfish-web/master-venv/include/site/python3.6/psycopg2 Check the logs for full command output.


MSG:

non-zero return code

###################################

I did not understand well what happen here. The problem seems linked to virtual env and psycog2.
I tried to install it via root with yum install python-psycopg2
It seems to work as the new error is :

###################################
TASK [bihealth.sodar_core_app : django -- prepare static files] 
fatal: [varfish]: FAILED! => {
    "changed": false,
    "cmd": "set -xeo pipefail\nsource /srv/varfish-web/master-venv/bin/activate\npython manage.py collectstatic --no-input\n",
    "delta": "0:00:00.295932",
    "end": "2020-10-22 13:52:44.474874",
    "rc": 1,
    "start": "2020-10-22 13:52:44.178942"
}

STDERR:

+ source /srv/varfish-web/master-venv/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/srv/varfish-web/master-venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/pgsql-12/bin
++ PATH=/srv/varfish-web/master-venv/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/pgsql-12/bin
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /srv/varfish-web/master-venv
++ PS1='(master-venv) '
++ export PS1
++ alias pydoc
++ '[' -n /bin/bash ']'
++ hash -r
+ python manage.py collectstatic --no-input
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/varfish-web/master-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/varfish-web/master-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/srv/varfish-web/master-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/srv/varfish-web/master-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/varfish-web/master-venv/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/srv/varfish-web/master-venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/varfish-web/master/config/settings/production.py", line 18, in <module>
    from .base import *  # noqa
  File "/srv/varfish-web/master/config/settings/base.py", line 235, in <module>
    import sqlalchemy.dialects.postgresql
ModuleNotFoundError: No module named 'sqlalchemy'


MSG:

non-zero return code

###################################
But this time even a yum install python-sqlalchemy does not work. This error persist.
Sorry for the long post but I am not so far away from the end.
Have you got any idea of what happened in there ?
Does something I have done is wrong ? 

Thanks a lot for your time,

Cheers,

Manuel
